# Generated by Django 5.2 on 2025-04-08 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_lapins', models.IntegerField()),
                ('food_quantity', models.FloatField()),
                ('number_cages', models.IntegerField()),
                ('money', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Regle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_food', models.FloatField()),
                ('price_cage', models.FloatField()),
                ('price_sale_lapin', models.FloatField()),
                ('conso_nourriture_1mois', models.FloatField()),
                ('conso_nourriture_2mois', models.FloatField()),
                ('conso_nourriture_3mois', models.FloatField()),
                ('nb_max_portee', models.IntegerField()),
                ('nb_max_cage', models.IntegerField()),
                ('age_min_gravide', models.IntegerField()),
                ('age_max_gravide', models.IntegerField()),
                ('duree_gestation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
                ('age', models.IntegerField()),
                ('etat', models.CharField(choices=[('P', 'Présent'), ('V', 'Vendu'), ('M', 'Mort'), ('G', 'Gravide')], max_length=1)),
                ('elevage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lap1.elevage')),
            ],
        ),
    ]
