# Generated by Django 5.2 on 2025-04-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevage',
            old_name='money',
            new_name='Argent_initial',
        ),
        migrations.RenameField(
            model_name='elevage',
            old_name='name',
            new_name='Nom_de_mon_elevage',
        ),
        migrations.RenameField(
            model_name='elevage',
            old_name='number_cages',
            new_name='Nombre_de_cages',
        ),
        migrations.RenameField(
            model_name='elevage',
            old_name='number_lapins',
            new_name='Nombre_de_lapins_femelles',
        ),
        migrations.RenameField(
            model_name='elevage',
            old_name='food_quantity',
            new_name='Quantité_de_nourriture_initiale',
        ),
        migrations.AddField(
            model_name='elevage',
            name='Nombre_de_lapins_males',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
