# Generated by Django 4.2 on 2025-04-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap1', '0002_rename_money_elevage_argent_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevage',
            name='Nombre_de_femelles_en_gestation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='Quantité_de_nourriture_initiale',
            field=models.IntegerField(),
        ),
    ]
