# Generated by Django 4.2 on 2025-04-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap1', '0004_rename_quantité_de_nourriture_initiale_elevage_quantite_de_nourriture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevage',
            old_name='Quantite_de_nourriture',
            new_name='quantite_de_nourriture',
        ),
        migrations.AlterField(
            model_name='elevage',
            name='Nombre_de_femelles_en_gestation',
            field=models.IntegerField(default=0),
        ),
    ]
