# Generated by Django 4.2 on 2025-04-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lap1', '0005_rename_quantite_de_nourriture_elevage_quantite_de_nourriture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevage',
            name='quantite_de_nourriture',
        ),
    ]
