# Generated by Django 4.2 on 2025-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap1', '0006_remove_elevage_quantite_de_nourriture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevage',
            name='Argent_initial',
            field=models.FloatField(verbose_name=int),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='Nombre_de_cages',
            field=models.IntegerField(verbose_name=int),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='Nombre_de_femelles_en_gestation',
            field=models.IntegerField(default=0, verbose_name=int),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='Nombre_de_lapins_femelles',
            field=models.IntegerField(verbose_name=int),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='Nombre_de_lapins_males',
            field=models.IntegerField(verbose_name=int),
        ),
    ]
