# Generated by Django 4.2 on 2025-04-17 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap1', '0008_alter_elevage_argent_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevage',
            name='Nourriture_disponible',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='Argent_initial',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='Nombre_de_cages',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='Nombre_de_femelles_en_gestation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='Nombre_de_lapins_femelles',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='elevage',
            name='Nombre_de_lapins_males',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
