# Generated by Django 5.1.7 on 2025-04-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap1', '0009_elevage_nourriture_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevage',
            name='mois',
            field=models.IntegerField(default=1),
        ),
    ]
