# Generated by Django 5.1.7 on 2025-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap1', '0010_elevage_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='mois_debut_gestation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
