# Generated by Django 4.2 on 2025-04-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lap1', '0011_individu_mois_debut_gestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='regle',
            name='price_buy_lapin',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='individu',
            name='etat',
            field=models.CharField(choices=[('P', 'Présent'), ('V', 'Vendu'), ('M', 'Mort'), ('G', 'Gravide'), ('S', 'Malade')], max_length=1),
        ),
    ]
